#:kivy 2.1

<Toolbar>:
    orientation: "rl-tb"
    padding: 5
    spacing: (5, 5)
    canvas.before:
        Color:
            rgb: (.1, .1, .1, 1)
        Rectangle:
            pos: self.pos
            size: self.size
    CustomButton:
        text: "o"
    CustomButton:
        text: "+"
        on_release:
            root.manager.transition.direction = "left"
            root.manager.current = "AddLayout"
